### ISSUE TITLE
Feature to allow skip-verify by github's user ids or code owners?

### ISSUE THREAD

**Issue by hu13** [actions-cool/verify-files-modify#27]
Hi there, I am thinking of using this action to prevent unauthorized users from modifying the workflows files in a github repo.

As you may know, github's write authorization on a repo for a user cannot be set on a fine grained level; for example only to a specific paths or folders. So a contributor with write access can modify any files on that repo, but the repo maintainer may want to protect the workflows files and only allows a subset of people (from a list of allowed github user ids or code owners) to modify them.

So I am wondering if we can add a feature for the action to skip verify if the user opening the PR is on the list of allowed github user ids or one of workflows files' code owners. I am thinking this is very similar to `skip-verify-authority` option, except it decides on user_ids rather than permissions.

Thanks.

**Comment by xrkffgg** [comment]
You can use `skip-verify-authority: admin`. And If you need, I can add a new variable like `skip-verify-users`.

**Comment by hu13** [comment]
I believe `skip-verify-users` will be more usable since not all workflows files' code owners are admin of the repo. Appreciate the fast reply.

**Comment by xrkffgg** [comment]
OK, I will notify you when done.

**Comment by xrkffgg** [comment]
```diff
+ verify-files-modify@v1.2.0
```
See README how to use. If have problem comment below.

**Comment by hu13** [comment]
I set up a test repo with the following workflow file: https://github.com/hu13/git-test/blob/master/.github/workflows/protect-workflows-files.yml that aims to run the verify check for everyone except `hu13`.
And I added my other github user account `hangkun13` as the collaborator, who then tries to modify the `github/workflows` which should not be allowed. However, the verifies seem to not working based on this test PR: https://github.com/hu13/git-test/pull/22

I am wondering if i am doing something incorrectly in the above test?

On the other hand, what if the collaborator deletes `protect-workflows-files.yml` that contains the verify-files-modify action logic altogether? Will this handle it? or is it out of scope?

**Comment by xrkffgg** [comment]
Try `verify-files-modify@v1.2.1`

**Comment by hu13** [comment]
https://github.com/hu13/git-test/pull/22/checks?check_run_id=2596942136 hits another error.

But the file modify check seems to be happening.

**Comment by xrkffgg** [comment]
Made a mistake. Wait a minute.

**Comment by xrkffgg** [comment]
> https://github.com/hu13/git-test/pull/22/checks?check_run_id=2596942136 hits another error.
> 
> But the file modify check seems to be happening.

Thanks for the feedback

**Comment by xrkffgg** [comment]
Try `verify-files-modify@v1.2.2`

**Comment by hu13** [comment]
@xrkffgg everything seems to work for all my test cases now.
Thanks so much for spending time on this.
